mozilla-services/find-package-rugaru

- fpr/run_pipeline.py
> log stacktraces from run_pipeline.py

- fpr/run_pipeline.py
> import pipelines from fpr namespace in run_pipeline.py

- Makefile
- fpr/containers.py
> fetch git tags (and othe refs) before checking them out

- Makefile
- Pipfile
- Pipfile.lock
- fpr/containers.py
- fpr/docker_log_reader.py
- fpr/pipelines/cargo_audit.py
- fpr/pipelines/cargo_metadata.py
- fpr/pipelines/crate_graph.py
- fpr/run_pipeline.py
- fpr/rx_util.py
- tests/unit/test_docker_log_reader.py
> Fix 27 crate graphviz graph

- Makefile
- README.md
- fpr/models/__init__.py
- fpr/models/pipeline.py
- fpr/pipelines/__init__.py
- fpr/pipelines/cargo_audit.py
- fpr/pipelines/cargo_metadata.py
- fpr/pipelines/crate_graph.py
- fpr/run_pipeline.py
- tests/unit/test_pipelines_serialize.py
fixes #25 and enables pipeline specific options
> Pipeline model sub cmd args

- incidents.jsonl
> add initial incidents jsonl file

- Makefile
- fpr/pipelines/crate_graph.py
> Fix 42 graph grouping

- Makefile
- fpr/containers.py
- fpr/pipelines/__init__.py
- fpr/pipelines/cargo_metadata.py
- fpr/pipelines/find_git_refs.py
- fpr/run_pipeline.py
- tests/fixtures/find_git_refs_serialized.json
- tests/fixtures/find_git_refs_unserialized.json
- tests/fixtures/mozilla_services_channelserver_repo_url.jsonl
- tests/unit/test_pipelines_serialize.py
> Add find git refs

- .dockerignore
- Dockerfile
- Makefile
- README.md
- fpr/run_pipeline.py
> Fix 68 package image

- Makefile
- fpr/containers.py
- fpr/models/__init__.py
Fixes the `fpr.containers.DockerRunException: ef5b7295b1544a29e8c5c6034d4ec3af12648fca931bc73dcf1c4e3c67be55da command git checkout 5a3e3967e90d65ca0d7a17b0466a3385898c3b6b failed with non-zero exit code 128 in https://circleci.com/gh/mozilla-services/syncstorage-rs/858
> Fetch git branch for ensure ref

- .circleci/config.yml
- Makefile
- README.md
> Publish tags from ci

- .circleci/config.yml
fix make not found error with docker-ci deploy image
> ci: save image to docker cache

- .circleci/config.yml
fix is the daemon running? error
> ci: start docker daemon before loading image

- .circleci/config.yml
- Dockerfile
- README.md
- bin/update_requirements.sh
- mypy.ini
for asyncio.Task.get_name() support for #91
> bump to python 3.8

- fpr/pipelines/github_metadata.py
- fpr/quiz_util.py
> Fix 117 gh meta pending

- fpr/models/github.py
- fpr/pipelines/github_metadata.py
- fpr/quiz_util.py
- tests/fixtures/REPO_LANGS_first_page_response_next_page.json
- tests/fixtures/REPO_VULN_ALERTS_first_page_response_next_page.json
- tests/fixtures/graphql/REPO_DEP_MANIFESTS_next_selection.graphql
- tests/fixtures/graphql/REPO_DEP_MANIFEST_DEPS_next_selection.graphql
- tests/fixtures/graphql/REPO_LANGS_next_selection.graphql
- tests/fixtures/graphql/REPO_VULN_ALERTS_next_selection.graphql
- tests/fixtures/graphql/REPO_VULN_ALERT_VULNS_next_selection.graphql
- tests/unit/test_github_models.py
fixes: #120 
refactors GH models
> pipelines: fix log strs for gh meta task statuses

- Makefile
- fpr/db/connect.py
- fpr/db/schema.py
- fpr/models/pipeline.py
- fpr/pipelines/__init__.py
- fpr/pipelines/save_to_db.py
- mypy.ini
- tests/unit/test_pipelines_serialize.py
fixes: #171
supercedes: #169
Note: save to db takes an input format with all the tasks in one jsonline that run tasks in repos and postprocess pipelines don't currently output
However, the overall pipeline will change with #166
> Save to db

- README.md
- bin/analyze_package.sh
- fpr/docker/containers.py
- fpr/models/language.py
- fpr/pipelines/postprocess.py
- fpr/pipelines/run_repo_tasks.py
- fpr/pipelines/save_to_db.py
> Fix 170 npm repo and commit

- bin/analyze_package.sh
- fpr/docker/containers.py
bugfixes for the analyze package script
> analyze pkg fixes

- fpr/models/language.py
unless tagged locally the find* pipelines 404 trying to run the image
> models: don't try to reuse buster base slim

- examples/api-v1.json
> API V1 example

- README.md
- design.md
Changes:
* document the pipeline API a bit (fixes #180)
* fix typo in design.md
* remove `cargo_metadata` pipeline example since that went away
* add analysis script examples using local db
* move examples to a scanner subheading
> updates docs

- bin/analyze_package.sh
- bin/analyze_repo.sh
Changes:
* fix parsing more weird npm reg repo urls
*  add verbose flag to `analyze_repo.sh` (defaulting to false)
> Script fixes

- fpr/docker/containers.py
- fpr/docker/log_reader.py
- fpr/pipelines/run_repo_tasks.py
fixes #183 
Considered using `itertools.accumulate` to get the next newline, but didn't see a nice way to use it.
> Fix 183 capture stderr

- examples/parents-v1.json
Cant get much simpler than this :)
The suggestion is to add a new API endpoint, with package manager, package name and version name as parameters.
It would then return all known package/version pairs that have the above as a dependency.
The UI could then, for example, show a count of the number of parents, and when clicked this could expand / redirect to a new page showing all of the parents.
No plan for paging server side at this stage, but could always add it client side first - I dont _think_ there should be huge amounts of data coming back...
> Add example parents API response

- bin/analyze_package.sh
- fpr/run_pipeline.py
Changes:
* fetch and save npm registry entry for the package name
* fetch and save npms.io scores for the package and its dependents
* log pipeline name when it finishes
> Save npm reg data

- MANIFEST.in
- fpr/__init__.py
- setup.py
for code reuse in mozilla-services/dependency-observatory
> add python packaging
